---
- name: Ensure autoload dir exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.vim/autoload"
    state: directory
    mode: 0755

- name: Install vimplug
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
    mode: 0644

- name: Write out vim.conf
  ansible.builtin.template:
    src: templates/vimrc.j2
    dest: "{{ ansible_env.HOME }}/.vimrc"
    mode: 0644

